name: crypt4ghfs
about: Fuse layer exposing Crypt4GH-encrypted files, as if they were decrypted.
args:
    - verbose:
        required: false
        short: v
        long: verbose
        about: Sets the level of verbosity
        takes_value: false
    - conf:
        required: true
        long: conf
        #about: TODO
        takes_value: true
        value_name: conf_path
    - MOUNTPOINT:
        required: true
