[package]
name = "crypt4ghfs"
version = "0.1.0"
authors = ["Roberto <roberto.ariosa@crg.eu>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/EGA-archive/crypt4ghfs-rust"
documentation = "https://docs.rs/crypt4ghfs"
readme = "README.md"
# TODO: Add missing categories

[lib]
name = "crypt4ghfs"
path = "src/lib.rs"

[[bin]]
name = "crypt4ghfs"
path = "src/main.rs"

[dependencies]
pretty_env_logger = "0.4.0"
fuse_mt = "0.5.1"
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
anyhow = "1.0"
toml = "0.5.8"
itertools = "0.10.0"
rpassword = "5.0.0"
crypt4gh = "0.1.3"
libc = "0.2.82"
time = "0.1.44"
fork = "0.1.18"
run_script = "0.6.3"